// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Merch struct {
	MerchID     int64
	Vendor      int64
	Status      int64
	Title       string
	Price       float64
	Description sql.NullString
	CreatedAt   time.Time
	ModifiedAt  time.Time
}
