VERSION 0.8
FROM golang:1.22-alpine
WORKDIR /app

deps:
  COPY ../../libs/db-package+artifact/* /libs/db-package
  COPY go.mod go.sum ./
  RUN go mod download

build:
  FROM +deps
  COPY main.go merch.go db_conn.go .
  RUN go build -o merch-rack .
  SAVE ARTIFACT merch-rack

test:
  FROM +deps
  COPY *.go .
  RUN go test

image:
  ARG EARTHLY_GIT_BRANCH
  ARG EARTHLY_GIT_SHORT_HASH
  ARG EARTHLY_GIT_TAG

  ARG buildenv=dev
  IF [ "$buildenv" = "prod" ]
    ARG TAG="latest"
  ELSE
    ARG TAG=$EARTHLY_GIT_BRANCH-$EARTHLY_GIT_SHORT_HASH
  END

  COPY +build/merch-rack .
  ENTRYPOINT ["/app/merch-rack"]
  SAVE IMAGE deanorhan/merch-rack:$TAG