# .github/workflows/ci.yml

name: Earthly +build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      # DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: 0.8.1
    - uses: actions/checkout@v4
    # - name: Docker Login
    #   run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: what version is installed?
      run: earthly --version
    - name: Run build
      run: earthly --ci +build